### ISSUE TITLE
Back To Top Button is not working in Ballerina Website

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-dev-website#1596]
**Description:**
There's this nice button on b.io `Back To Top`.  But it seems like it is not working properly. 

**OS, Browser, other environment details and versions:**    
OS: macOS BigSur
Browser: Safari 14.0.1

**Steps to reproduce:**
Check the button on https://ballerina.io/swan-lake/learn/by-example/#table-of-content

**Comment by praneesha** [comment]
The button should be fixed and updated to direct to the top of the page and not the TOC.

**Comment by praneesha** [comment]
Button is directed to the top of the page instead of directing to the TOC via https://github.com/ballerina-platform/ballerina-dev-website/pull/1668.

**Comment by ThisaruGuruge** [comment]
This is still not working on the table of contents page.

Tried with Safari 14.0.2 on macOS BigSur.

> The button should be fixed and updated to direct to the top of the page and not the TOC.
I just put the ToC link to check the button functionality of the ToC page.

**Comment by praneesha** [comment]
This is fixed in live now.
