### ISSUE TITLE
Top menu is overlapping with Ballerina logo

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2715]
**Description:**
$subject in [1]

[1] https://ballerina.io/learn/by-example/introduction/

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/16300038/129772767-a4f2b003-3980-4459-a700-683b0247f46c.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
CLosing since this is fixed now.

**Comment by anupama-pathirage** [comment]
Issue is still there in firefox hence opening. 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16300038/133204482-2c039fda-fba6-4094-8eb2-638076e1d04d.png">

**Comment by anupama-pathirage** [comment]
Also the top links are moving. 


See the below URLs

[1] https://ballerina.io/learn/by-example/introduction/

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/16300038/133204984-6af93ace-30a0-4c9a-b6f1-6347c21fcda6.png">

[2] https://ballerina.io/learn/by-example/consuming-services

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/16300038/133205109-8c5763e1-e127-4799-9347-2e1fb2f5ae6c.png">

**Comment by praneesha** [comment]
Closing since these issues are fixed now. Checked in Firfefox also.
