### ISSUE TITLE
Code `copy` icon only copies only the first line

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-dev-website#8143]
## Description
$subject

## Steps to reproduce
In the following sample
https://ballerina.io/learn/manage-data-persistence-with-bal-persist/#try-the-service

When we click the copy icon to copy the code, it only copies the first line of it.
It could be happening in other pages too.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as the issue is fixed. Reopen if there are concerns.

**Comment by sm1990** [comment]
Reopening as the issue is still there for terminal (bash) commands with multiple lines.

**Comment by Ishad-M-I-M** [comment]
Hi. @keizer619 @sm1990 .
I'm interested in taking up this issue

**Comment by keizer619** [comment]
Hi @Ishad-M-I-M 
You can work on this issue. 

To help you get started, here are some essential resources:

1. Understanding [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md):
Learn what Ballerina is all about: Ballerina Platform
2. How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
3. Contributing to the Ballerina library:
If you're interested in contributing to our library, here are the guidelines: [Library Contribution Guide](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/CONTRIBUTING.md)
4. [Learn Ballerina](https://ballerina.io/learn/):
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: Learn Ballerina
5. Get Help and Connect:
Ask technical questions on Stack Overflow with with [Ballerina tag ](https://stackoverflow.com/questions/tagged/ballerina) and join our Discord community [Ballerina Discord](https://discord.com/invite/ballerinalang)

**Comment by Mannxxx** [comment]
Hi. @keizer619 @sm1990 .
I'm interested in working on this issue.

**Comment by sm1990** [comment]
Hi @Ishad-M-I-M have you started working on this issue? Since you have picked up https://github.com/ballerina-platform/ballerina-dev-website/issues/6983 as well, shall we assign this to @Mannxxx ?

**Comment by Ishad-M-I-M** [comment]
> Hi @Ishad-M-I-M have you started working on this issue? Since you have picked up https://github.com/ballerina-platform/ballerina-dev-website/issues/6983 as well, shall we assign this to @Mannxxx ?

No problem

**Comment by sm1990** [comment]
Thank you @Ishad-M-I-M. @Mannxxx you can work on this. Ill assign it to you.

**Comment by sm1990** [comment]
@Mannxxx let me know if you have any questions.

**Comment by sm1990** [comment]
Hi @Mannxxx ,
Any update on this issue?

**Comment by sm1990** [comment]
Hi @Mannxxx,

FYA @Ishad-M-I-M is working on a related issue and has sent the following PR (https://github.com/ballerina-platform/ballerina-dev-website/pull/9550). He has updated the shiki version. Its still under review. I hope it doesn't conflict with your work. Let me know if there is any issue.

**Comment by Ishad-M-I-M** [comment]
> Hi @Mannxxx , Any update on this issue?

If there's no update can I work on this?.

**Comment by sm1990** [comment]
@Mannxxx have you started working on this. If not shall I assign it to @Ishad-M-I-M ?

**Comment by sm1990** [comment]
@Ishad-M-I-M you can start working on this. i'll assign it to you.
